# Generated by Django 4.1.1 on 2023-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
