# Generated by Django 4.1.1 on 2023-11-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIt', '0002_alter_question_topic_delete_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quesion',
            new_name='question',
        ),
    ]
