# Generated by Django 4.1.1 on 2023-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIt', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
